cbis:
  dataset: MammographyClassification
  dataset_dir: /home/mammography_data/input/CBIS_DDSM/data
  ann_files:
    train: /home/mammography_data/input/CBIS_DDSM/train.csv
    valid: /home/mammography_data/input/CBIS_DDSM/test.csv
    test: /home/mammography_data/input/CBIS_DDSM/test.csv
  kwargs:
    ratio: 1
    windowing: false
    mask_dir: /home/mammography_data/input/CBIS_DDSM/masks
  train_kwargs:
    p_mask: 0
  valid_kwargs:
    p_mask: 0
  test_kwargs:
    p_mask: 0
  ignore_classes: []
  class_map:
    BENIGN_WITHOUT_CALLBACK: 0
    BENIGN: 0
    MALIGNANT: 1
