inbreast:
  dataset: MammographyClassification
  dataset_dir: s3://inbreast/data/
  ann_files:
    train: /home/a.komarov/data/mammography/inbreast/train_splitted.csv
    #valid: /home/a.komarov/data/mammography/inbreast/valid_splitted.csv
    test: /home/a.komarov/data/mammography/inbreast/test.csv
  kwargs:
    ratio: 1
    windowing: false
    mask_dir: /home/mammography_data/input/INBreast/masks
  train_kwargs:
    p_mask: 0
  valid_kwargs:
    p_mask: 0
  test_kwargs:
    p_mask: 0
  ignore_classes: 
    - "3"
    - "4a"
    - "4b"
    - "4c"
  class_map:
    "1": 0
    "2": 0
    "5": 1
    "6": 1
